//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandleModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigParameter
    {
        public int CPId { get; set; }
        public int StationID { get; set; }
        public Nullable<double> Origin { get; set; }
        public Nullable<int> SoundverCount { get; set; }
        public Nullable<int> HSpeedverCount { get; set; }
        public Nullable<int> MSpeedverCount { get; set; }
        public Nullable<int> LSpeedverCount { get; set; }
        public Nullable<double> LeftDistance { get; set; }
        public Nullable<double> RightDistance { get; set; }
        public Nullable<double> LLeftCft { get; set; }
        public Nullable<double> MLeftCft { get; set; }
        public Nullable<double> HLeftCft { get; set; }
        public Nullable<double> LRightCft { get; set; }
        public Nullable<double> MRightCft { get; set; }
        public Nullable<double> HRightCft { get; set; }
        public Nullable<double> BottomElevWaterGau { get; set; }
        public Nullable<double> TopElevWaterGau { get; set; }
        public Nullable<double> RiverBottEle { get; set; }
        public Nullable<double> GasgaugeParameter1 { get; set; }
        public Nullable<double> GasgaugeParameter2 { get; set; }
        public Nullable<double> FloatgaugeParameter1 { get; set; }
        public Nullable<double> FloatgaugeParameter2 { get; set; }
        public Nullable<double> RopewayLength { get; set; }
        public Nullable<double> StartDistance { get; set; }
        public Nullable<double> LargeSecDepth { get; set; }
        public Nullable<double> BaseWaterLevel { get; set; }
        public Nullable<double> StopWaterLev { get; set; }
        public Nullable<double> StopTemperature { get; set; }
        public Nullable<double> WarnWaterValue { get; set; }
        public Nullable<double> WarnFlowValue { get; set; }
        public Nullable<double> WarnVelValue { get; set; }
        public Nullable<byte> SentState { get; set; }
        public string RevTime { get; set; }
    }
}
