//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandleModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualTestTable
    {
        public int MTId { get; set; }
        public int StationID { get; set; }
        public Nullable<System.DateTime> MTTestTime { get; set; }
        public Nullable<double> WaterLevalue { get; set; }
        public Nullable<double> Flow { get; set; }
        public string DataType { get; set; }
    }
}
