//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandleModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasureRecord
    {
        public int MMId { get; set; }
        public Nullable<int> StationID { get; set; }
        public Nullable<int> MeasureMark { get; set; }
        public string TypeMark { get; set; }
        public string ReceiveBackMark { get; set; }
        public string VerticalMark { get; set; }
        public Nullable<int> SetOutMark { get; set; }
        public string ReachZeroMark { get; set; }
        public Nullable<int> CompletedMark { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public string FailMark { get; set; }
        public string HandleAccount { get; set; }
        public string VolatMark { get; set; }
        public string DataContent { get; set; }
    }
}
