//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandleModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MinuFlowRate
    {
        public long MFRId { get; set; }
        public int StationID { get; set; }
        public Nullable<double> FlowRateData { get; set; }
        public Nullable<double> Voltage { get; set; }
        public Nullable<double> Discharge { get; set; }
        public Nullable<System.DateTime> RecTime { get; set; }
        public Nullable<System.DateTime> TestTime { get; set; }
        public string Remarks { get; set; }
        public Nullable<double> CarVoltage { get; set; }
    }
}
