//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandleModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NSY_RTRUN
    {
        public string STCD { get; set; }
        public string DATATYPE { get; set; }
        public System.DateTime TM { get; set; }
        public Nullable<decimal> DA { get; set; }
        public Nullable<decimal> DP { get; set; }
        public decimal DI { get; set; }
        public Nullable<decimal> PDR { get; set; }
        public Nullable<decimal> DQ { get; set; }
        public Nullable<decimal> DV { get; set; }
        public System.DateTime INSERTTM { get; set; }
    }
}
