//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandleModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadRainfalldata
    {
        public int RRId { get; set; }
        public int StationID { get; set; }
        public Nullable<System.DateTime> RRTestTime { get; set; }
        public Nullable<double> RRData1 { get; set; }
        public Nullable<double> RRData3 { get; set; }
        public Nullable<double> RRData2 { get; set; }
        public Nullable<double> RRData4 { get; set; }
        public Nullable<double> RRData5 { get; set; }
        public Nullable<double> RRData6 { get; set; }
        public Nullable<double> RRData7 { get; set; }
        public Nullable<double> RRData8 { get; set; }
        public Nullable<double> RRData9 { get; set; }
        public Nullable<double> RRData10 { get; set; }
        public Nullable<double> RRData11 { get; set; }
        public Nullable<double> RRData12 { get; set; }
    }
}
