//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandleModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RainfallData
    {
        public int RId { get; set; }
        public int StationID { get; set; }
        public Nullable<double> RainfallData1 { get; set; }
        public Nullable<double> RainfallData2 { get; set; }
        public Nullable<double> RainfallData3 { get; set; }
        public Nullable<double> RainfallData4 { get; set; }
        public Nullable<double> RainfallData5 { get; set; }
        public Nullable<double> RainfallData6 { get; set; }
        public Nullable<double> RainfallData7 { get; set; }
        public Nullable<double> RainfallData8 { get; set; }
        public Nullable<double> RainfallData9 { get; set; }
        public Nullable<double> RainfallData10 { get; set; }
        public Nullable<double> RainfallData11 { get; set; }
        public Nullable<double> RainfallData12 { get; set; }
        public Nullable<double> TotalRain { get; set; }
        public Nullable<double> Temperature { get; set; }
        public Nullable<byte> State { get; set; }
        public string PacketType { get; set; }
        public Nullable<System.DateTime> ReceiveTime { get; set; }
        public Nullable<System.DateTime> TestTime { get; set; }
    }
}
