//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandleModel.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RWEntities : DbContext
    {
        public RWEntities()
            : base("name=RWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<B_UserRoleRelation> B_UserRoleRelation { get; set; }
        public virtual DbSet<Base_Module> Base_Module { get; set; }
        public virtual DbSet<Base_ProvinceCity> Base_ProvinceCity { get; set; }
        public virtual DbSet<CityInfo> CityInfo { get; set; }
        public virtual DbSet<ConfigParameter> ConfigParameter { get; set; }
        public virtual DbSet<CorrectionFactor> CorrectionFactor { get; set; }
        public virtual DbSet<CountryInfo> CountryInfo { get; set; }
        public virtual DbSet<EvaporationData> EvaporationData { get; set; }
        public virtual DbSet<FlowParArea> FlowParArea { get; set; }
        public virtual DbSet<FlowTable> FlowTable { get; set; }
        public virtual DbSet<HandleLog> HandleLog { get; set; }
        public virtual DbSet<hydStation> hydStation { get; set; }
        public virtual DbSet<ManualTestTable> ManualTestTable { get; set; }
        public virtual DbSet<ManVelData> ManVelData { get; set; }
        public virtual DbSet<MeasuredParameter> MeasuredParameter { get; set; }
        public virtual DbSet<MeasureRecord> MeasureRecord { get; set; }
        public virtual DbSet<MinuFlowRate> MinuFlowRate { get; set; }
        public virtual DbSet<NSY_RTRUN> NSY_RTRUN { get; set; }
        public virtual DbSet<OriginalData> OriginalData { get; set; }
        public virtual DbSet<ProvinceInfo> ProvinceInfo { get; set; }
        public virtual DbSet<RadRainfalldata> RadRainfalldata { get; set; }
        public virtual DbSet<RainfallData> RainfallData { get; set; }
        public virtual DbSet<RTUTestPlan> RTUTestPlan { get; set; }
        public virtual DbSet<SedimentData> SedimentData { get; set; }
        public virtual DbSet<SoundverData> SoundverData { get; set; }
        public virtual DbSet<SpeedData> SpeedData { get; set; }
        public virtual DbSet<UpdateRecord> UpdateRecord { get; set; }
        public virtual DbSet<WaterLevData> WaterLevData { get; set; }
        public virtual DbSet<WM_Area> WM_Area { get; set; }
        public virtual DbSet<WM_Company> WM_Company { get; set; }
        public virtual DbSet<WM_ModulePermission> WM_ModulePermission { get; set; }
        public virtual DbSet<WM_Role> WM_Role { get; set; }
        public virtual DbSet<WM_User> WM_User { get; set; }
        public virtual DbSet<WM_UserRoleRelation> WM_UserRoleRelation { get; set; }
    }
}
