//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandleModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTUTestPlan
    {
        public int TPId { get; set; }
        public int StationID { get; set; }
        public string LWTestPlan { get; set; }
        public string MWTestPlan { get; set; }
        public string HWTestPlan { get; set; }
        public int CPId { get; set; }
        public byte SendState { get; set; }
    }
}
