//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandleModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SedimentData
    {
        public int SeId { get; set; }
        public int StationID { get; set; }
        public Nullable<double> SedimentData1 { get; set; }
        public Nullable<double> SedimentData2 { get; set; }
        public Nullable<double> SedimentData3 { get; set; }
        public Nullable<double> SedimentData4 { get; set; }
        public Nullable<double> SedimentData5 { get; set; }
        public Nullable<double> SedimentData6 { get; set; }
        public Nullable<double> SedimentData7 { get; set; }
        public Nullable<double> SedimentData8 { get; set; }
        public Nullable<double> SedimentData9 { get; set; }
        public Nullable<double> SedimentData10 { get; set; }
        public Nullable<double> SedimentData11 { get; set; }
        public Nullable<double> SedimentData12 { get; set; }
        public Nullable<byte> State { get; set; }
        public string PacketType { get; set; }
        public Nullable<System.DateTime> ReceiveTime { get; set; }
        public Nullable<System.DateTime> TestTime { get; set; }
    }
}
