//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandleModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoundverData
    {
        public int SvdId { get; set; }
        public int StationID { get; set; }
        public Nullable<int> DataOrder { get; set; }
        public Nullable<double> StartDistL { get; set; }
        public Nullable<double> VerData { get; set; }
        public int CPId { get; set; }
        public string RevTime { get; set; }
        public Nullable<int> TestRecord { get; set; }
    }
}
