//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandleModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpeedData
    {
        public int SdId { get; set; }
        public Nullable<int> StationID { get; set; }
        public Nullable<int> DataOrder { get; set; }
        public Nullable<double> StartDistV { get; set; }
        public Nullable<double> RiverElva { get; set; }
        public Nullable<double> CorrecFactor { get; set; }
        public Nullable<double> HCoeff { get; set; }
        public Nullable<double> MCoeff { get; set; }
        public Nullable<double> LCoeff { get; set; }
        public Nullable<double> HCoeffA { get; set; }
        public Nullable<double> HCoeffB { get; set; }
        public Nullable<double> MCoeffA { get; set; }
        public Nullable<double> MCoeffB { get; set; }
        public Nullable<double> LCoeffA { get; set; }
        public Nullable<double> LCoeffB { get; set; }
        public string DataType { get; set; }
        public int CPId { get; set; }
        public string RevTime { get; set; }
    }
}
