//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandleModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdateRecord
    {
        public int UDId { get; set; }
        public Nullable<int> StationID { get; set; }
        public string StationName { get; set; }
        public Nullable<int> UpdateMark { get; set; }
        public string FilePath { get; set; }
        public string FilePathB { get; set; }
        public Nullable<int> ResponseMark { get; set; }
        public Nullable<int> CompletedMark { get; set; }
        public Nullable<int> Argement { get; set; }
        public Nullable<int> SerialNumber { get; set; }
        public string TypeMark { get; set; }
        public string DeviceType { get; set; }
    }
}
