//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandleModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaterLevData
    {
        public int WLId { get; set; }
        public Nullable<int> StationID { get; set; }
        public Nullable<System.DateTime> TestTime { get; set; }
        public Nullable<double> WLData1 { get; set; }
        public Nullable<double> WLData2 { get; set; }
        public Nullable<double> WLData3 { get; set; }
        public Nullable<double> WLData4 { get; set; }
        public Nullable<double> WLData5 { get; set; }
        public Nullable<double> WLData6 { get; set; }
        public Nullable<double> WLData7 { get; set; }
        public Nullable<double> WLData8 { get; set; }
        public Nullable<double> WLData9 { get; set; }
        public Nullable<double> WLData10 { get; set; }
        public Nullable<double> WLData11 { get; set; }
        public Nullable<double> WLData12 { get; set; }
        public Nullable<double> TotalData { get; set; }
        public Nullable<byte> DataType { get; set; }
        public string RevTime { get; set; }
    }
}
