//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandleModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WM_Company
    {
        public string CompanyId { get; set; }
        public string ParentId { get; set; }
        public string FullName { get; set; }
        public string Tel { get; set; }
        public string AreaID { get; set; }
        public string AreaName { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Enabled { get; set; }
        public Nullable<int> SortCode { get; set; }
        public Nullable<int> DeleteMark { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUserId { get; set; }
        public string ModifyUserName { get; set; }
        public Nullable<int> StationID { get; set; }
        public string StationName { get; set; }
        public string Province { get; set; }
        public string CityId { get; set; }
        public string City { get; set; }
        public string CountyId { get; set; }
        public string County { get; set; }
        public string ProvinceId { get; set; }
    }
}
