//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTU_WaterData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_PPTN_R
    {
        public string STCD { get; set; }
        public System.DateTime TM { get; set; }
        public Nullable<decimal> DRP { get; set; }
        public Nullable<decimal> INTV { get; set; }
        public Nullable<decimal> PDR { get; set; }
        public Nullable<decimal> DYP { get; set; }
        public string WTH { get; set; }
    }
}
